version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_SERVER_URL: "http://localhost:8081"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
