name: Run Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Format the code"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run frontend tests
      run: cd course-matrix/frontend && npm install && npm run test
    - name: Run backend tests
      run: cd course-matrix/backend && npm install && npm run test