name: Run Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run frontend tests
      run: cd course-matrix/frontend && yarn && yarn test
    - name: Run backend tests
      run: cd course-matrix/backend && yarn && yarn test